### PR TITLE
Update README with explicit expected experience

### PR DESCRIPTION
**Pull request by andygeorge**

### CODE REVIEW

**Comment by djuber** [comment]
Self-assessment of technical competence is going to close the door to people who were competent enough to _use_ the repo successfully, while not being ready to contribute or having higher standards for themselves than they needed to.

Maybe clarify that "while the recipes and scripts here are expected to work for the limited scenarios we tested against, modification of the recipes, or altering the deployed environment, may require familiarity with the following layers of the tech stack we built with", and "ongoing maintenance of the deployed system may require interacting with any  of these technologies"?

I'm all in favor of the "forem is complex software", that echos language in other projects. I just worry we're gatekeeping by requiring "high familiarity" with a long list of technologies.

**Comment by andygeorge** [comment]
> Maybe clarify that "while the recipes and scripts here are expected to work for the limited scenarios we tested against, modification of the recipes, or altering the deployed environment, may require familiarity with the following layers of the tech stack we built with", and "ongoing maintenance of the deployed system may require interacting with any of these technologies"?

+1 to this language, I'll get that in

>  I just worry we're gatekeeping by requiring "high familiarity" with a long list of technologies.

Agree that `high familiarity` is not the best phrase here, I'll change that. IMO we do still want to call out that list of technologies with some level of experience - we know that internal testing by those without much Ansible experience was difficult and required some level of assistance.

**Review by djuber — APPROVED** [review]

**Comment by pkfrank** [comment]
> we know that internal testing by those without much Ansible experience was difficult and required some level of assistance.

My $0.02 — while this is true, the internal testing folks (myself included) were going through it without the assistance of deeper guides and walkthroughs.  With more tutorials from @cmgorton and others, I imagine we'll be able to make selfhosting increasingly accessible.

**Comment by andygeorge** [comment]
@pkfrank agreed, and that's some of the impetus behind this PR - those tutorials and outside guidance are not (yet?) part of this repo, so it is important to set some technical expectations for those using the repo by itself.

**Review by jdoss — APPROVED** [review]
One of the first goals of this repo has always been to give people a framework for setting up Forem in a highly reproducible way that is free of high costs and complexity. That being said, that freedom doesn't mean end users won't have to do some work on their end to be successful in using this framework. I think these changes help set better expectations than the original copy.

**Pull request merged**
